# Training
Train Decision Tree classifier on several subsets of features

In [57]:
import sklearn
from glob import glob
import pandas as pd

In [ ]:
train_csv = 'data/dev/dev-clean-whisper-large-v2-hypotheses-preprocessed.csv'
train_df = pd.read_csv(train_csv)
# train_df = train_df.reindex(sorted(train_df.columns), axis=1)
test_csv = 'data/test/test-clean-whisper-large-v2-hypotheses-preprocessed.csv'
test_df = pd.read_csv(test_csv)
# test_df = test_df.reindex(sorted(test_df.columns), axis=1)

train_df

edit_type  next_word_len  next_word_pos_is_$  next_word_pos_is_.  \
0            0.0              3                   0                   0   
1            0.0              2                   0                   0   
2            0.0              1                   0                   0   
3            0.0              7                   0                   0   
4            0.0              5                   0                   0   
...          ...            ...                 ...                 ...   
85773        3.0              3                   0                   0   
85774        3.0              3                   0                   0   
85775        3.0              3                   0                   0   
85776        3.0              3                   0                   0   
85777        3.0              3                   0                   0   

       next_word_pos_is_</s>  next_word_pos_is_<s>  next_word_pos_is_CC  \
0                          0                     0                    0   
1                          0                     0                    0   
2                          0                     0                    0   
3                          0                     0                    0   
4                          0                     0                    0   
...                      ...                   ...                  ...   
85773                      0                     0                    0   
85774                      0                     0                    0   
85775                      0                     0                    0   
85776                      0                     0                    0   
85777                      0                     0                    0   

       next_word_pos_is_CD  next_word_pos_is_DT  next_word_pos_is_EX  ...  \
0                        0                    0                    0  ...   
1                        0                    0                    0  ...   
2                        0                    1                    0  ...   
3                        0                    0                    0  ...   
4                        0                    0                    0  ...   
...                    ...                  ...                  ...  ...   
85773                    0                    0                    0  ...   
85774                    0                    0                    0  ...   
85775                    0                    0                    0  ...   
85776                    0                    0                    0  ...   
85777                    0                    0                    0  ...   

       word_pos_is_VBD  word_pos_is_VBG  word_pos_is_VBN  word_pos_is_VBP  \
0                    0                0                0                0   
1                    1                0                0                0   
2                    0                0                0                0   
3                    0                0                0                0   
4                    0                0                0                0   
...                ...              ...              ...              ...   
85773                0                0                0                0   
85774                0                0                0                0   
85775                0                0                0                0   
85776                0                0                0                0   
85777                0                0                0                0   

       word_pos_is_VBZ  word_pos_is_WDT  word_pos_is_WP  word_pos_is_WP$  \
0                    0                0               0                0   
1                    0                0               0                0   
2                    0                0               0                0   
3                    0                0            

In [59]:
test_df

edit_type  next_word_len  next_word_pos_is_$  next_word_pos_is_.  \
0            0.0              8                   0                   0   
1            0.0              2                   0                   0   
2            0.0              3                   0                   0   
3            0.0              5                   0                   0   
4            0.0              6                   0                   0   
...          ...            ...                 ...                 ...   
54455        0.0              3                   0                   0   
54456        0.0              4                   0                   0   
54457        0.0             10                   0                   0   
54458        0.0              4                   0                   0   
54459        0.0              4                   0                   0   

       next_word_pos_is_</s>  next_word_pos_is_<s>  next_word_pos_is_CC  \
0                          0                     0                    0   
1                          0                     0                    0   
2                          0                     0                    0   
3                          0                     0                    0   
4                          0                     0                    0   
...                      ...                   ...                  ...   
54455                      0                     0                    0   
54456                      0                     0                    0   
54457                      0                     0                    0   
54458                      0                     0                    0   
54459                      1                     0                    0   

       next_word_pos_is_CD  next_word_pos_is_DT  next_word_pos_is_EX  ...  \
0                        0                    0                    0  ...   
1                        0                    0                    0  ...   
2                        0                    0                    0  ...   
3                        0                    0                    0  ...   
4                        0                    0                    0  ...   
...                    ...                  ...                  ...  ...   
54455                    0                    0                    0  ...   
54456                    0                    0                    0  ...   
54457                    0                    0                    0  ...   
54458                    0                    0                    0  ...   
54459                    0                    0                    0  ...   

       word_pos_is_VBD  word_pos_is_VBG  word_pos_is_VBN  word_pos_is_VBP  \
0                    0                0                0                0   
1                    1                0                0                0   
2                    0                0                0                0   
3                    0                0                0                0   
4                    0                0                0                0   
...                ...              ...              ...              ...   
54455                0                0                0                0   
54456                0                0                0                0   
54457                0                0                0                0   
54458                0                0                0                0   
54459                0                0                0                0   

       word_pos_is_VBZ  word_pos_is_WDT  word_pos_is_WP  word_pos_is_WP$  \
0                    0                0               0                0   
1                    0                0               0                0   
2                    0                0               0                0   
3                    0                0            

In [60]:
feat_cols = [col for col in train_df.columns if col!='edit_type' and 'POS' not in col]
pos_feats = [col for col in feat_cols if 'pos' in col]
len_feats = [col for col in feat_cols if 'len' in col]
freq_feats = [col for col in feat_cols if 'freq' in col]
identity_feats = [col for col in feat_cols if 'same' in col]
prev_word_feats = [col for col in feat_cols if col.startswith('prev')]
curr_word_feats = [col for col in feat_cols if col.startswith('word')]
next_word_feats = [col for col in feat_cols if col.startswith('next')]

In [61]:
feat_groups = {
    "all": feat_cols,
    "pos": pos_feats,
    "len": len_feats,
    "frequency": freq_feats,
    "identity": identity_feats,
    "prev_word": prev_word_feats,
    "curr_word": curr_word_feats,
    "next_word": next_word_feats,
}

In [62]:
y = train_df['edit_type'].to_numpy()
y_test = test_df['edit_type'].to_numpy()

for feat_name, feats in feat_groups.items():
    print(feat_name)
    tree_clf = sklearn.tree.DecisionTreeClassifier(max_depth=40)
    X = train_df[feats].to_numpy()
    X_test = test_df[feats].to_numpy()
    tree_clf.fit(X, y)
    y_hat = tree_clf.predict(X_test)
    f1_score = sklearn.metrics.f1_score(y_test, y_hat, average=None)
    print(f1_score)
    

all
[0.94602372 0.11176158 0.01303215]
pos
[0.96581881 0.06685237 0.08035004]
len
[0.9248253  0.05235888 0.14817814]
frequency
[0.91523481 0.09551869 0.08111702]
identity
[0.97743397 0.         0.20282279]
prev_word
[0.93556752 0.03703704 0.0575411 ]
curr_word
[0.94758816 0.23697556 0.10528801]
next_word
[0.92653045 0.01486989 0.06274624]
